version: '2'
services:
  rancher-logs-collector:
    image: leodotcloud/rancher-logs-collector:dev
    labels:
      io.rancher.container.create_agent: 'true'
      io.rancher.container.agent.role: 'environmentAdmin'
    logging:
      driver: json-file
      options:
        max-size: 25m
        max-file: '2'
